#!/bin/bash
set -e

# Read database credentials from environment variables
MYSQL_HOST=$MYSQL_HOST
MYSQL_PORT=$MYSQL_PORT
MYSQL_DB=$MYSQL_DB
MYSQL_USER=$MYSQL_USER
MYSQL_PASSWORD=$MYSQL_PASSWORD

clickhouse client -n <<-EOSQL
        DROP DATABASE IF EXISTS $MYSQL_DB;
        CREATE DATABASE $MYSQL_DB ENGINE = MySQL('$MYSQL_HOST:$MYSQL_PORT', '$MYSQL_DB', '$MYSQL_USER', '$MYSQL_PASSWORD');
EOSQL
